// Generated by CoffeeScript 1.8.0
$(window).load(function() {
  return firebase.auth().onAuthStateChanged(function(user) {
    return $('.reddit-login').on('click', function(e) {
      var k, params, url, v;
      params = ((function() {
        var _ref, _results;
        _ref = {
          client_id: 'Ag0ViT48lPnFiQ',
          response_type: 'code',
          state: '123',
          redirect_uri: 'https://us-central1-botnet-a2e6f.cloudfunctions.net/redditAuth',
          duration: 'permanent',
          scope: 'vote identity'
        };
        _results = [];
        for (k in _ref) {
          v = _ref[k];
          _results.push("" + k + "=" + (encodeURIComponent(v)));
        }
        return _results;
      })()).join('&');
      url = "https://www.reddit.com/api/v1/authorize?" + params;
      return window.open(url);
    });
  });
});
